framework:
    messenger:
        failure_transport: failed
        transports:
            mailer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 5
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'
        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': mailer
