security:
    encoder:
        App\Infrastructure\Security\User:
            algorithm: argon2i
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            id: App\Infrastructure\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            pattern: ^/
#            custom_authenticators:
#                - App\Infrastructure\Security\Authenticator\WebAuthenticator
    access_control: