
security_register:
  path: /register
  methods: GET|POST
  controller: App\UserInterface\Controller\RegistrationController

security_login:
  path: /login
  methods: GET|POST
  controller: App\UserInterface\Controller\LoginController
  
home:
  path: /
  methods: GET
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: home.html.twig