parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\:
    resource: '../src/Infrastructure'
    exclude: '../src/Infrastructure/{Test}'

#  App\UserInterface\:
#    resource: '../src/UserInterface'
#
#  App\UserInterface\Controller\:
#    resource: '../src/UserInterface/Controller'
#    tags: ['controller.service_arguments']

  Domain\:
    resource: '../Domain/src'